[package]
name = "iris"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
serenity = "0.12.5"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.22"
